from docx import Document
from typing import Dict, Any

class DocxGenerator:
    def generate(self, filepath: str, data: Dict[str, Any]):
        doc = Document()
        doc.add_heading('Department of Legal Metrology', 0)
        doc.add_heading(f"Inspection Report: {data.get('inspection_number', 'N/A')}", level=1)
        
        doc.add_paragraph(f"Product: {data.get('product_name', 'N/A')}")
        doc.add_paragraph(f"Score: {data.get('score', 0)}% - {data.get('status', 'N/A')}")
        
        doc.add_heading('Results Summary', level=2)
        for res in data.get('results', []):
            doc.add_paragraph(f"{res.get('field_name')}: {res.get('status')}", style='List Bullet')
            
        doc.add_paragraph("Disclaimer: Auto-generated by Legal Metrology Compliance Checker.")
        doc.save(filepath)
