from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from typing import Dict, Any

class PDFGenerator:
    def generate(self, filepath: str, data: Dict[str, Any]):
        c = canvas.Canvas(filepath, pagesize=letter)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, 750, "Department of Legal Metrology")
        
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, 710, f"Inspection Report: {data.get('inspection_number', 'N/A')}")
        
        c.setFont("Helvetica", 10)
        c.drawString(50, 680, f"Product: {data.get('product_name', 'N/A')}")
        c.drawString(50, 660, f"Score: {data.get('score', 0)}% - {data.get('status', 'N/A')}")
        
        c.drawString(50, 620, "Results Summary:")
        y = 600
        for res in data.get('results', [])[:15]:  # Limit for demo
            c.drawString(60, y, f"- {res.get('field_name')}: {res.get('status')}")
            y -= 20
            if y < 100:
                c.showPage()
                y = 750
        
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(50, 50, "Disclaimer: Auto-generated by Legal Metrology Compliance Checker.")
        
        c.save()
